In [ ]:
import numpy as np
import pandas as pd
pd.options.mode.chained_assignment = None


In [ ]:
df=pd.read_csv('https://drive.google.com/uc?export=download&id=12KieiuP24jrrpTQqT4lj9L5iUXyr63s1')

In [ ]:
features_kept=['_STATE','SEXVAR','GENHLTH','PHYSHLTH','MENTHLTH','PRIMINSR','PERSDOC3','CHECKUP1','EXERANY2','SLEPTIM1','CVDINFR4','CHCOCNC1','ADDEPEV3','CHCKDNY2','DIABETE4','MARITAL','VETERAN3','WEIGHT2','HEIGHT3','DEAF','BLIND','DECIDE','DIFFWALK','DIFFDRES','DIFFALON','COVIDPOS','CNCRDIFF','CNCRAGE','CNCRTYP2','CSRVPAIN','CIMEMLOS','CDHOUSE','CDASSIST','CDHELP','CDSOCIAL','LSATISFY','EMTSUPRT','SDHISOLT','EMPLOY1','SDHFOOD1','SDHBILLS','SDHUTILS','SDHTRNSP','SDHSTRE1','_URBSTAT','_IMPRACE','_RFHLTH','_PHYS14D','_MENT14D','_TOTINDA','_MICHD','_ASTHMS1','_DRDXAR2','_AGE80','_CHLDCNT','_EDUCAG','_INCOMG1','_SMOKER3','_CURECI2','_DRNKWK2','_AIDTST4']
df2 = df[features_kept]

In [ ]:
df3 = df2[['DIFFDRES', 'DIFFALON', 'COVIDPOS', 'CNCRDIFF', 'CNCRTYP2', 'LSATISFY', 'EMTSUPRT', 'SDHISOLT', 'EMPLOY1']]


In [ ]:
df3.head(100)

DIFFDRES  DIFFALON  COVIDPOS  CNCRDIFF  CNCRTYP2  LSATISFY  EMTSUPRT  \
0        2.0       2.0       2.0       NaN       NaN       1.0       1.0   
1        2.0       2.0       2.0       NaN       NaN       1.0       1.0   
2        2.0       2.0       2.0       NaN       NaN       1.0       3.0   
3        2.0       1.0       2.0       NaN       NaN       1.0       1.0   
4        2.0       2.0       2.0       NaN       NaN       2.0       2.0   
..       ...       ...       ...       ...       ...       ...       ...   
95       2.0       2.0       2.0       NaN       NaN       1.0       1.0   
96       1.0       1.0       2.0       NaN       NaN       4.0       4.0   
97       2.0       2.0       2.0       NaN       NaN       1.0       1.0   
98       2.0       2.0       2.0       NaN       NaN       1.0       1.0   
99       2.0       1.0       1.0       NaN       NaN       2.0       2.0   

    SDHISOLT  EMPLOY1  
0        5.0      7.0  
1        4.0      2.0  
2        4.0      7.0  
3        5.0      7.0  
4        4.0      7.0  
..       ...      ...  
95       5.0      7.0  
96       3.0      7.0  
97       5.0      7.0  
98       5.0      7.0  
99       3.0      7.0  

[100 rows x 9 columns]

In [ ]:
for col in df3:
  print("col name is",col,"unique is",df3[col].unique())

col name is DIFFDRES unique is [2. 1. 9. 7.]
col name is DIFFALON unique is [2. 1. 9. 7.]
col name is COVIDPOS unique is [2. 1. 9. 3. 7.]
col name is CNCRDIFF unique is [nan  3.  1.  2.  9.  7.]
col name is CNCRTYP2 unique is [nan 12. 22. 20. 15. 16.  6.  5. 30. 29. 77.  7. 23.  2.  4.  1. 28. 14.
 21. 10. 24. 19. 13. 18. 99. 17. 25.  8. 27.  3. 26.  9. 11.]
col name is LSATISFY unique is [ 1.  2.  3. nan  4.  9.  7.]
col name is EMTSUPRT unique is [ 1.  3.  2.  5. nan  7.  4.  9.]
col name is SDHISOLT unique is [ 5.  4.  3. nan  2.  1.  9.  7.]
col name is EMPLOY1 unique is [7. 2. 8. 1. 5. 9. 3. 6. 4.]


In [ ]:
def ToBinary(df, column_name):
  df2 = df.copy()
  df2[column_name] = df2[column_name].astype(int)
  df2[column_name].replace(2, 0, inplace=True)
  return df2

In [ ]:
# col name is DIFFDRES unique is [2. 1. 9. 7.]
# col name is DIFFALON unique is [2. 1. 9. 7.]
# col name is COVIDPOS unique is [2. 1. 9. 3. 7.]

test = ToBinary(df3, 'DIFFDRES')
test = ToBinary(test, 'DIFFALON')
test = ToBinary(test, 'COVIDPOS')

In [ ]:
test['CNCRTYP2'].fillna(111, inplace=True)
test['LSATISFY'].fillna(111, inplace=True)
test['EMTSUPRT'].fillna(111, inplace=True)
test['SDHISOLT'].fillna(111, inplace=True)
test['CNCRDIFF'].fillna(7, inplace=True)

print("Unique values for LSATISFY column:")
print(test['LSATISFY'].unique())

print("Unique values for EMTSUPRT column:")
print(test['EMTSUPRT'].unique())

print("Unique values for SDHISOLT column:")
print(test['SDHISOLT'].unique())

print("Unique values for CNCRDIFF column:")
print(test['CNCRDIFF'].unique())


Unique values for LSATISFY column:
[  1.   2.   3. 111.   4.   9.   7.]
Unique values for EMTSUPRT column:
[  1.   3.   2.   5. 111.   7.   4.   9.]
Unique values for SDHISOLT column:
[  5.   4.   3. 111.   2.   1.   9.   7.]
Unique values for CNCRDIFF column:
[7. 3. 1. 2. 9.]


In [ ]:
cancer_mapping_dict = {
    1: 'Bladder',
    2: 'Blood',
    3: 'Bone',
    4: 'Brain',
    5: 'Breast',
    6: 'Cervix/Cervical',
    7: 'Colon',
    8: 'Esophagus/Esophageal',
    9: 'Gallbladder',
    10: 'Kidney',
    11: 'Larynx-trachea',
    12: 'Leukemia',
    13: 'Liver',
    14: 'Lung',
    15: 'Lymphoma',
    16: 'Melanoma',
    17: 'Mouth/tongue/lip',
    18: 'Ovary/Ovarian',
    19: 'Pancreas/Pancreatic',
    20: 'Prostate',
    21: 'Rectum/Rectal',
    22: 'Skin (non-melanoma)',
    23: 'Skin (don’t know what kind)',
    24: 'Soft tissue (muscle or fat)',
    25: 'Stomach',
    26: 'Testis/Testicular',
    27: 'Throat - pharynx',
    28: 'Thyroid',
    29: 'Uterus/Uterine',
    30: 'Other',
    77: 'Don’t know/Not sure',
    99: 'Refused',
    111: 'No Cancer'
}
test['CNCRTYP2'] = test['CNCRTYP2'].replace(cancer_mapping_dict)

In [ ]:
satisfaction_mapping = {
    1: 'Very satisfied',
    2: 'Satisfied',
    3: 'Dissatisfied',
    4: 'Very dissatisfied',
    7: 'Don’t know/Not sure',
    9: 'Refused',
    111: 'Missing'
}
test['LSATISFY'] = test['LSATISFY'].replace(satisfaction_mapping)

In [ ]:
employ_mapping_dict = {
    1: "Employed for wages",
    2: "Self-employed",
    3: "Out of work for 1 year or more",
    4: "Out of work for less than 1 year",
    5: "A homemaker",
    6: "A student",
    7: "Retired",
    8: "Unable to work",
    9: "Refused",
}

test['EMPLOY1'] = test['EMPLOY1'].replace(employ_mapping_dict)


In [ ]:
emotional_support_mapping = {
    1: 'Always',
    2: 'Usually',
    3: 'Sometimes',
    4: 'Rarely',
    5: 'Never',
    7: 'Don’t know/Not sure',
    9: 'Refused',
    111: 'Missing'
}
test['EMTSUPRT'] = test['EMTSUPRT'].replace(emotional_support_mapping)

In [ ]:
social_isolation_mapping = {
    1: 'Always',
    2: 'Usually',
    3: 'Sometimes',
    4: 'Rarely',
    5: 'Never',
    7: 'Don’t know/Not Sure',
    9: 'Refused',
    111: 'Missing'
}
test['SDHISOLT'] = test['SDHISOLT'].replace(social_isolation_mapping)

In [ ]:
cancer_type_mapping = {
    1: 'Only one',
    2: 'Two',
    3: 'Three or more',
    7: 'Don’t know/Not Sure',
    9: 'Refused',
}
test['CNCRDIFF'] = test['CNCRDIFF'].replace(cancer_type_mapping)

In [ ]:

one_hot_encoded = pd.get_dummies(test['CNCRTYP2'],dtype='int')
test = pd.concat([test, one_hot_encoded], axis=1)
test.drop(columns=['CNCRTYP2'], inplace=True)

one_hot_encoded = pd.get_dummies(test['LSATISFY'],dtype='int')
test = pd.concat([test, one_hot_encoded], axis=1)
test.drop(columns=['LSATISFY'], inplace=True)

one_hot_encoded = pd.get_dummies(test['EMPLOY1'],dtype='int')
test = pd.concat([test, one_hot_encoded], axis=1)
test.drop(columns=['EMPLOY1'], inplace=True)

one_hot_encoded = pd.get_dummies(test['EMTSUPRT'],dtype='int')
one_hot_encoded.columns = ['emotional_support_' + col.replace(' ', '_') for col in one_hot_encoded.columns]
test = pd.concat([test, one_hot_encoded], axis=1)
test.drop(columns=['EMTSUPRT'], inplace=True)

one_hot_encoded = pd.get_dummies(test['SDHISOLT'],dtype='int')
one_hot_encoded.columns = ['isolation_' + col.replace(' ', '_') for col in one_hot_encoded.columns]
test = pd.concat([test, one_hot_encoded], axis=1)
test.drop(columns=['SDHISOLT'], inplace=True)

one_hot_encoded = pd.get_dummies(test['CNCRDIFF'],dtype='int')
one_hot_encoded.columns = ['no_of_cancers_' + col.replace(' ', '_') for col in one_hot_encoded.columns]
test = pd.concat([test, one_hot_encoded], axis=1)
test.drop(columns=['CNCRDIFF'], inplace=True)

In [ ]:
test.shape

(64675, 73)

In [ ]:
test.drop(columns=['Missing'], inplace=True)

In [ ]:
'Missing' in test.columns

False

In [ ]:
test.shape

(64675, 72)

In [ ]:
test.columns

Index(['DIFFDRES', 'DIFFALON', 'COVIDPOS', 'Bladder', 'Blood', 'Bone', 'Brain',
       'Breast', 'Cervix/Cervical', 'Colon', 'Don’t know/Not sure',
       'Esophagus/Esophageal', 'Gallbladder', 'Kidney', 'Larynx-trachea',
       'Leukemia', 'Liver', 'Lung', 'Lymphoma', 'Melanoma', 'Mouth/tongue/lip',
       'No Cancer', 'Other', 'Ovary/Ovarian', 'Pancreas/Pancreatic',
       'Prostate', 'Rectum/Rectal', 'Refused', 'Skin (don’t know what kind)',
       'Skin (non-melanoma)', 'Soft tissue (muscle or fat)', 'Stomach',
       'Testis/Testicular', 'Throat - pharynx', 'Thyroid', 'Uterus/Uterine',
       'Dissatisfied', 'Don’t know/Not sure', 'Refused', 'Satisfied',
       'Very dissatisfied', 'Very satisfied', 'A homemaker', 'A student',
       'Employed for wages', 'Out of work for 1 year or more',
       'Out of work for less than 1 year', 'Refused', 'Retired',
       'Self-employed', 'Unable to work', 'emotional_support_Always',
       'emotional_support_Don’t_know/Not_sure', 'emotional_s

In [ ]:

pattern = '.*Refused'

# Use filter to select columns based on the regex pattern and drop them
test.drop(columns=test.filter(regex=pattern).columns, inplace=True)

# Now, check the shape of the DataFrame after dropping columns
print(test.shape)



(64675, 66)


In [ ]:
pattern = '.*Missing'

# Use filter to select columns based on the regex pattern and drop them
test.drop(columns=test.filter(regex=pattern).columns, inplace=True)

# Now, check the shape of the DataFrame after dropping columns
print(test.shape)

(64675, 64)


In [ ]:
test.drop(columns=["No Cancer"],inplace=True)

In [ ]:
test.drop(columns=["Don’t know/Not sure"],inplace=True)

In [ ]:
pattern = '.*Don’t_know/Not_Sure'

# Use filter to select columns based on the regex pattern and drop them
test.drop(columns=test.filter(regex=pattern).columns, inplace=True)

# Now, check the shape of the DataFrame after dropping columns
print(test.shape)

(64675, 59)


In [ ]:
test.columns

Index(['DIFFDRES', 'DIFFALON', 'COVIDPOS', 'Bladder', 'Blood', 'Bone', 'Brain',
       'Breast', 'Cervix/Cervical', 'Colon', 'Esophagus/Esophageal',
       'Gallbladder', 'Kidney', 'Larynx-trachea', 'Leukemia', 'Liver', 'Lung',
       'Lymphoma', 'Melanoma', 'Mouth/tongue/lip', 'Other', 'Ovary/Ovarian',
       'Pancreas/Pancreatic', 'Prostate', 'Rectum/Rectal',
       'Skin (don’t know what kind)', 'Skin (non-melanoma)',
       'Soft tissue (muscle or fat)', 'Stomach', 'Testis/Testicular',
       'Throat - pharynx', 'Thyroid', 'Uterus/Uterine', 'Dissatisfied',
       'Satisfied', 'Very dissatisfied', 'Very satisfied', 'A homemaker',
       'A student', 'Employed for wages', 'Out of work for 1 year or more',
       'Out of work for less than 1 year', 'Retired', 'Self-employed',
       'Unable to work', 'emotional_support_Always',
       'emotional_support_Don’t_know/Not_sure', 'emotional_support_Never',
       'emotional_support_Rarely', 'emotional_support_Sometimes',
       'emotional_

In [ ]:
test.shape

(64675, 59)

In [ ]:
test.to_csv('Lavanya.csv', index=False)