In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('https://drive.google.com/uc?export=download&id=12KieiuP24jrrpTQqT4lj9L5iUXyr63s1')

In [3]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler


In [4]:
features_kept=['_STATE','SEXVAR','GENHLTH','PHYSHLTH','MENTHLTH','PRIMINSR','PERSDOC3','CHECKUP1','EXERANY2','SLEPTIM1','CVDINFR4','CHCOCNC1','ADDEPEV3','CHCKDNY2','DIABETE4','MARITAL','VETERAN3','WEIGHT2','HEIGHT3','DEAF','BLIND','DECIDE','DIFFWALK','DIFFDRES','DIFFALON','COVIDPOS','CNCRDIFF','CNCRAGE','CNCRTYP2','CSRVPAIN','CIMEMLOS','CDHOUSE','CDASSIST','CDHELP','CDSOCIAL','LSATISFY','EMTSUPRT','SDHISOLT','SDHEMPLY','SDHFOOD1','SDHBILLS','SDHUTILS','SDHTRNSP','SDHSTRE1','_URBSTAT','_IMPRACE','_RFHLTH','_PHYS14D','_MENT14D','_TOTINDA','_MICHD','_ASTHMS1','_DRDXAR2','_AGE80','_CHLDCNT','_EDUCAG','_INCOMG1','_SMOKER3','_CURECI2','_DRNKWK2','_AIDTST4']

In [5]:
df1 = df[features_kept]

In [6]:
df1.shape

(64675, 61)

In [7]:
features_kept1=['SDHFOOD1','SDHBILLS','SDHUTILS','SDHTRNSP','SDHSTRE1','_URBSTAT','_IMPRACE','_RFHLTH','_PHYS14D','_MENT14D']

In [8]:
df2 = df1[features_kept1]

In [9]:
df2.shape

(64675, 10)

In [10]:
#df['B'] = df['B'].replace({3: 2, 4: 2})
df2['SDHUTILS'].unique()
#df2['SDHUTILS']=df2['SDHUTILS'].replace({3.0: 2.0, 4: 2})

array([ 2.,  1., nan,  9.,  7.])

In [11]:
df2['SDHUTILS'].dtypes

dtype('float64')

In [12]:
#df['B'] = df['B'].replace(3, np.nan)
#df.loc[df['B'].isin([3.0, 4.0]), 'B'] = np.nan
df2.loc[df2['SDHUTILS'].isin([7.0, 9.0]), 'SDHUTILS']=np.nan

<ipython-input-12-ee58c77f9879>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[df2['SDHUTILS'].isin([7.0, 9.0]), 'SDHUTILS']=np.nan


In [13]:
df2['SDHUTILS'].unique()

array([ 2.,  1., nan])

In [14]:
df2.loc[~df2['SDHUTILS'].isin([1.0]), 'SDHUTILS'] = 0.0

<ipython-input-14-5bbf251fe2a7>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[~df2['SDHUTILS'].isin([1.0]), 'SDHUTILS'] = 0.0


In [15]:
df2['SDHUTILS'].unique()

array([0., 1.])

In [16]:
df2['SDHFOOD1'].unique()

array([ 5.,  3.,  1.,  4., nan,  9.,  2.,  7.])

In [17]:
df2.loc[df2['SDHFOOD1'].isin([7.0, 9.0]), 'SDHFOOD1']= np.nan
df2['SDHFOOD1'].unique()

<ipython-input-17-55c84950c128>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[df2['SDHFOOD1'].isin([7.0, 9.0]), 'SDHFOOD1']= np.nan


array([ 5.,  3.,  1.,  4., nan,  2.])

In [18]:
df2['SDHFOOD1'].fillna(0, inplace=True)
df2['SDHFOOD1'].unique()

<ipython-input-18-c49fc48e63e6>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['SDHFOOD1'].fillna(0, inplace=True)


array([5., 3., 1., 4., 0., 2.])

In [19]:
#SDHBILLS
df2['SDHBILLS'].unique()

array([ 2.,  7., nan,  1.,  9.])

In [20]:
df2.loc[df2['SDHBILLS'].isin([7.0, 9.0]), 'SDHBILLS']=np.nan
df2['SDHBILLS'].unique()

<ipython-input-20-a8294d46805c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[df2['SDHBILLS'].isin([7.0, 9.0]), 'SDHBILLS']=np.nan


array([ 2., nan,  1.])

In [21]:
df2.loc[~df2['SDHBILLS'].isin([1.0]), 'SDHBILLS'] = 0.0
df2['SDHBILLS'].unique()

<ipython-input-21-4f63a182425b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[~df2['SDHBILLS'].isin([1.0]), 'SDHBILLS'] = 0.0


array([0., 1.])

In [22]:
#SDHTRNSP
df2['SDHTRNSP'].unique()

array([ 2., nan,  1.,  9.,  7.])

In [23]:
df2.loc[df2['SDHTRNSP'].isin([7.0, 9.0]), 'SDHTRNSP']=np.nan
df2['SDHTRNSP'].unique()

<ipython-input-23-acf80a7477c7>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[df2['SDHTRNSP'].isin([7.0, 9.0]), 'SDHTRNSP']=np.nan


array([ 2., nan,  1.])

In [24]:
df2.loc[~df2['SDHTRNSP'].isin([1.0]), 'SDHTRNSP'] = 0.0
df2['SDHTRNSP'].unique()

<ipython-input-24-58aa5696e3fa>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[~df2['SDHTRNSP'].isin([1.0]), 'SDHTRNSP'] = 0.0


array([0., 1.])

In [25]:
#SDHSTRE1
df2['SDHSTRE1'].unique()

array([ 5.,  4.,  3.,  2., nan,  7.,  1.,  9.])

In [26]:
df2.loc[df2['SDHSTRE1'].isin([7.0, 9.0]), 'SDHSTRE1']=0.0
df2['SDHSTRE1'].unique()

<ipython-input-26-53467a7c0fb8>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[df2['SDHSTRE1'].isin([7.0, 9.0]), 'SDHSTRE1']=0.0


array([ 5.,  4.,  3.,  2., nan,  0.,  1.])

In [27]:
df2['SDHSTRE1'].fillna(0, inplace=True)
df2['SDHSTRE1'].unique()

<ipython-input-27-0ed83841c829>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['SDHSTRE1'].fillna(0, inplace=True)


array([5., 4., 3., 2., 0., 1.])

In [28]:
df2['_URBSTAT'].unique()

array([1., 2.])

In [29]:
#_RFHLTH
df2['_RFHLTH'].unique()

array([1., 2., 9.])

In [30]:
df2.loc[df2['_RFHLTH'].isin([9.0]), '_RFHLTH']=np.nan
df2['_RFHLTH'].unique()

<ipython-input-30-4d4d1715258e>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[df2['_RFHLTH'].isin([9.0]), '_RFHLTH']=np.nan


array([ 1.,  2., nan])

In [31]:
df2.loc[~df2['_RFHLTH'].isin([1.0]), '_RFHLTH'] = 0.0
df2['_RFHLTH'].unique()

<ipython-input-31-9b7d3254c158>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[~df2['_RFHLTH'].isin([1.0]), '_RFHLTH'] = 0.0


array([1., 0.])

In [32]:
#_PHYS14D
df2['_PHYS14D'].unique()

array([1., 2., 3., 9.])

In [33]:
df2.loc[df2['_PHYS14D'].isin([9.0]), '_PHYS14D']= np.nan
df2['_PHYS14D'].fillna(0, inplace=True)
df2['_PHYS14D'].unique()

<ipython-input-33-2ff68756355e>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[df2['_PHYS14D'].isin([9.0]), '_PHYS14D']= np.nan
<ipython-input-33-2ff68756355e>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['_PHYS14D'].fillna(0, inplace=True)


array([1., 2., 3., 0.])

In [34]:
#_MENT14D
df2['_MENT14D'].unique()

array([1., 9., 2., 3.])

In [35]:
df2.loc[df2['_MENT14D'].isin([9.0]), '_MENT14D']=0.0
df2['_MENT14D'].unique()

<ipython-input-35-0e0469a5f254>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[df2['_MENT14D'].isin([9.0]), '_MENT14D']=0.0


array([1., 0., 2., 3.])

In [36]:
df2['_IMPRACE'].unique()

array([1., 5., 2., 6., 4., 3.])

In [37]:
IMPRACE=pd.get_dummies(df2['_IMPRACE'])

In [38]:
IMPRACE

1.0    2.0    3.0    4.0    5.0    6.0
0       True  False  False  False  False  False
1       True  False  False  False  False  False
2       True  False  False  False  False  False
3       True  False  False  False  False  False
4       True  False  False  False  False  False
...      ...    ...    ...    ...    ...    ...
64670   True  False  False  False  False  False
64671  False  False  False  False   True  False
64672   True  False  False  False  False  False
64673   True  False  False  False  False  False
64674   True  False  False  False  False  False

[64675 rows x 6 columns]

In [39]:
new_columns = ['_IMPRACE:White', '_IMPRACE:Black', '_IMPRACE:Asian',
               '_IMPRACE:American Indian/Alaskan Native','_IMPRACE:	Hispanic',
               '_IMPRACE:	Other race, Non-Hispanic']

In [40]:
IMPRACE.columns = new_columns
IMPRACE

_IMPRACE:White  _IMPRACE:Black  _IMPRACE:Asian  \
0                True           False           False   
1                True           False           False   
2                True           False           False   
3                True           False           False   
4                True           False           False   
...               ...             ...             ...   
64670            True           False           False   
64671           False           False           False   
64672            True           False           False   
64673            True           False           False   
64674            True           False           False   

       _IMPRACE:American Indian/Alaskan Native  _IMPRACE:\tHispanic  \
0                                        False                False   
1                                        False                False   
2                                        False                False   
3                                        False                False   
4                                        False                False   
...                                        ...                  ...   
64670                                    False                False   
64671                                    False                 True   
64672                                    False                False   
64673                                    False                False   
64674                                    False                False   

       _IMPRACE:\tOther race, Non-Hispanic  
0                                    False  
1                                    False  
2                                    False  
3                                    False  
4                                    False  
...                                    ...  
64670                                False  
64671                                False  
64672                                False  
64673                                False  
64674                                False  

[64675 rows x 6 columns]

In [41]:
IMPRACE1 = IMPRACE.astype(int)
IMPRACE1

_IMPRACE:White  _IMPRACE:Black  _IMPRACE:Asian  \
0                   1               0               0   
1                   1               0               0   
2                   1               0               0   
3                   1               0               0   
4                   1               0               0   
...               ...             ...             ...   
64670               1               0               0   
64671               0               0               0   
64672               1               0               0   
64673               1               0               0   
64674               1               0               0   

       _IMPRACE:American Indian/Alaskan Native  _IMPRACE:\tHispanic  \
0                                            0                    0   
1                                            0                    0   
2                                            0                    0   
3                                            0                    0   
4                                            0                    0   
...                                        ...                  ...   
64670                                        0                    0   
64671                                        0                    1   
64672                                        0                    0   
64673                                        0                    0   
64674                                        0                    0   

       _IMPRACE:\tOther race, Non-Hispanic  
0                                        0  
1                                        0  
2                                        0  
3                                        0  
4                                        0  
...                                    ...  
64670                                    0  
64671                                    0  
64672                                    0  
64673                                    0  
64674                                    0  

[64675 rows x 6 columns]

In [42]:
df2 = pd.concat([df2, IMPRACE1], axis=1)


In [43]:
df2

SDHFOOD1  SDHBILLS  SDHUTILS  SDHTRNSP  SDHSTRE1  _URBSTAT  _IMPRACE  \
0           5.0       0.0       0.0       0.0       5.0       1.0       1.0   
1           5.0       0.0       1.0       0.0       5.0       1.0       1.0   
2           5.0       0.0       0.0       0.0       4.0       1.0       1.0   
3           5.0       0.0       0.0       0.0       5.0       1.0       1.0   
4           5.0       0.0       0.0       0.0       4.0       1.0       1.0   
...         ...       ...       ...       ...       ...       ...       ...   
64670       5.0       0.0       0.0       0.0       5.0       1.0       1.0   
64671       3.0       1.0       0.0       1.0       1.0       1.0       5.0   
64672       5.0       0.0       0.0       0.0       4.0       1.0       1.0   
64673       5.0       0.0       0.0       0.0       3.0       1.0       1.0   
64674       5.0       0.0       0.0       0.0       5.0       1.0       1.0   

       _RFHLTH  _PHYS14D  _MENT14D  _IMPRACE:White  _IMPRACE:Black  \
0          1.0       1.0       1.0               1               0   
1          1.0       1.0       1.0               1               0   
2          1.0       2.0       0.0               1               0   
3          1.0       1.0       1.0               1               0   
4          0.0       2.0       2.0               1               0   
...        ...       ...       ...             ...             ...   
64670      1.0       1.0       1.0               1               0   
64671      0.0       3.0       3.0               0               0   
64672      1.0       2.0       1.0               1               0   
64673      1.0       1.0       1.0               1               0   
64674      1.0       2.0       1.0               1               0   

       _IMPRACE:Asian  _IMPRACE:American Indian/Alaskan Native  \
0                   0                                        0   
1                   0                                        0   
2                   0                                        0   
3                   0                                        0   
4                   0                                        0   
...               ...                                      ...   
64670               0                                        0   
64671               0                                        0   
64672               0                                        0   
64673               0                                        0   
64674               0                                        0   

       _IMPRACE:\tHispanic  _IMPRACE:\tOther race, Non-Hispanic  
0                        0                                    0  
1                        0                                    0  
2                        0                                    0  
3                        0                                    0  
4                        0                                    0  
...                    ...                                  ...  
64670                    0                                    0  
64671                    1                                    0  
64672                    0                                    0  
64673                    0                                    0  
64674                    0                                    0  

[64675 rows x 16 columns]

In [44]:
df2 = df2.drop('_IMPRACE', axis=1)
df2

SDHFOOD1  SDHBILLS  SDHUTILS  SDHTRNSP  SDHSTRE1  _URBSTAT  _RFHLTH  \
0           5.0       0.0       0.0       0.0       5.0       1.0      1.0   
1           5.0       0.0       1.0       0.0       5.0       1.0      1.0   
2           5.0       0.0       0.0       0.0       4.0       1.0      1.0   
3           5.0       0.0       0.0       0.0       5.0       1.0      1.0   
4           5.0       0.0       0.0       0.0       4.0       1.0      0.0   
...         ...       ...       ...       ...       ...       ...      ...   
64670       5.0       0.0       0.0       0.0       5.0       1.0      1.0   
64671       3.0       1.0       0.0       1.0       1.0       1.0      0.0   
64672       5.0       0.0       0.0       0.0       4.0       1.0      1.0   
64673       5.0       0.0       0.0       0.0       3.0       1.0      1.0   
64674       5.0       0.0       0.0       0.0       5.0       1.0      1.0   

       _PHYS14D  _MENT14D  _IMPRACE:White  _IMPRACE:Black  _IMPRACE:Asian  \
0           1.0       1.0               1               0               0   
1           1.0       1.0               1               0               0   
2           2.0       0.0               1               0               0   
3           1.0       1.0               1               0               0   
4           2.0       2.0               1               0               0   
...         ...       ...             ...             ...             ...   
64670       1.0       1.0               1               0               0   
64671       3.0       3.0               0               0               0   
64672       2.0       1.0               1               0               0   
64673       1.0       1.0               1               0               0   
64674       2.0       1.0               1               0               0   

       _IMPRACE:American Indian/Alaskan Native  _IMPRACE:\tHispanic  \
0                                            0                    0   
1                                            0                    0   
2                                            0                    0   
3                                            0                    0   
4                                            0                    0   
...                                        ...                  ...   
64670                                        0                    0   
64671                                        0                    1   
64672                                        0                    0   
64673                                        0                    0   
64674                                        0                    0   

       _IMPRACE:\tOther race, Non-Hispanic  
0                                        0  
1                                        0  
2                                        0  
3                                        0  
4                                        0  
...                                    ...  
64670                                    0  
64671                                    0  
64672                                    0  
64673                                    0  
64674                                    0  

[64675 rows x 15 columns]

In [45]:
df2.to_csv('keni_data.csv', index=False)

In [46]:
from google.colab import files
files.download('keni_data.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>